### ISSUE TITLE
ImportError: No module named video

### ISSUE THREAD

**Issue by eonurk** [fkmclane/python-ardrone#1]
Hello everyone,

When I make `import ardrone` 

it gives me the following error; 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ardrone/__init__.py", line 4, in <module>
    from ardrone.drone import ARDrone
  File "ardrone/drone.py", line 12, in <module>
    import ardrone.network
  File "ardrone/network.py", line 15, in <module>
    import ardrone.video
ImportError: No module named video

Any help would be perfect :)

**Comment by lilyinstarlight** [comment]
This means for some reason, the video C module was not compiled when you installed the package. Did you install it with './setup.py install' or something similar? If so, what was the output for the command?

**Comment by eonurk** [comment]
Yes, I did python setup.py install.

There were 3 fatal errors due to ffmpeg libraries but I installed them one by one. However, Im not sure about the exact final output. I will post it as soon as possible.

**Comment by eonurk** [comment]
Issuing the command 
`sudo python setup.py install` gave me this result;

running install
running build
running build_py
running build_ext
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/ardrone-0.1.egg-info
Writing /usr/local/lib/python2.7/dist-packages/ardrone-0.1.egg-info

Then the same error occured during import ardrone.

**Comment by lilyinstarlight** [comment]
Do a `python setup.py clean` then a `python setup.py build` and paste the output (and if you wouldn't mind, could you put it in a [code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/)?).

**Comment by eonurk** [comment]
This is the output it gives.
```
running build
running build_py
copying ardrone/network.py -> build/lib.linux-aarch64-2.7/ardrone
running build_ext
```

**Comment by lilyinstarlight** [comment]
It still isn't rebuilding the whole package which is what I need the output for. Try deleting the 'build' folder and doing `python setup.py build` again.

**Comment by lilyinstarlight** [comment]
It should look something like this:

```
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/ardrone
copying ardrone/__init__.py -> build/lib.linux-x86_64-3.5/ardrone
copying ardrone/at.py -> build/lib.linux-x86_64-3.5/ardrone
copying ardrone/client.py -> build/lib.linux-x86_64-3.5/ardrone
copying ardrone/constant.py -> build/lib.linux-x86_64-3.5/ardrone
copying ardrone/drone.py -> build/lib.linux-x86_64-3.5/ardrone
copying ardrone/navdata.py -> build/lib.linux-x86_64-3.5/ardrone
copying ardrone/network.py -> build/lib.linux-x86_64-3.5/ardrone
running build_ext
building 'ardrone.video' extension
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/ardrone
x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python3.5m -c ardrone/video.c -o build/temp.linux-x86_64-3.5/ardrone/video.o
ardrone/video.c: In function ‘video_decode’:
ardrone/video.c:183:2: warning: ‘avcodec_decode_video2’ is deprecated [-Wdeprecated-declarations]
  frame_size = avcodec_decode_video2(context, frame, &got_frame, &packet);
  ^
In file included from ardrone/video.c:3:0:
/usr/include/libavcodec/avcodec.h:4812:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^
ardrone/video.c:192:2: warning: ‘avpicture_get_size’ is deprecated [-Wdeprecated-declarations]
  image_size = avpicture_get_size(AV_PIX_FMT_RGB24, image_width, image_height)*sizeof(uint8_t);
  ^
In file included from ardrone/video.c:3:0:
/usr/include/libavcodec/avcodec.h:5468:5: note: declared here
 int avpicture_get_size(enum AVPixelFormat pix_fmt, int width, int height);
     ^
x86_64-pc-linux-gnu-gcc -pthread -shared build/temp.linux-x86_64-3.5/ardrone/video.o -L/usr/lib64 -lavcodec -lavformat -lavutil -lswscale -lpython3.5m -o build/lib.linux-x86_64-3.5/ardrone/video.cpython-35m-x86_64-linux-gnu.so
```

**Comment by eonurk** [comment]
```
running build
running build_py
creating build
creating build/lib.linux-aarch64-2.7
creating build/lib.linux-aarch64-2.7/ardrone
copying ardrone/client.py -> build/lib.linux-aarch64-2.7/ardrone
copying ardrone/navdata.py -> build/lib.linux-aarch64-2.7/ardrone
copying ardrone/network.py -> build/lib.linux-aarch64-2.7/ardrone
copying ardrone/at.py -> build/lib.linux-aarch64-2.7/ardrone
copying ardrone/__init__.py -> build/lib.linux-aarch64-2.7/ardrone
copying ardrone/drone.py -> build/lib.linux-aarch64-2.7/ardrone
copying ardrone/constant.py -> build/lib.linux-aarch64-2.7/ardrone
running build_ext
building 'ardrone.video' extension
creating build/temp.linux-aarch64-2.7
creating build/temp.linux-aarch64-2.7/ardrone
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c ardrone/video.c -o build/temp.linux-aarch64-2.7/ardrone/video.o
aarch64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-aarch64-2.7/ardrone/video.o -lavcodec -lavformat -lavutil -lswscale -o build/lib.linux-aarch64-2.7/ardrone/video.so


```

**Comment by eonurk** [comment]
I take the video stream via a very simple opencv code:

```python
import cv2 

cam = cv2.VideoCapture('tcp://192.168.1.1:5555')
while (True):
    _, im = cam.read()
    cv2.imshow('frame',im)
    cv2.waitKey(1)

```

It works great with your client.py. However, when I make a process on images, it is slowed down and makes the process frame by frame and I think it's related with TCP connection of the Ar drone. It constantly sends images and I cannot take image unless I process it. So, is there a way around it? Any TCP configuration for python or any arrangement that I can make?

**Comment by lilyinstarlight** [comment]
The C module for decoding the video is a lot faster. It seems to build alright, so I'm not sure why it wouldn't be running.

Can you try importing ardrone from the 'build/lib.linux-aarch64-2.7' directory?

**Comment by eonurk** [comment]
Okey, thank you I got it working now. But, I don't know how to use C module.

**Comment by lilyinstarlight** [comment]
It should automatically work, assuming there is communication with the drone and the package was built correctly. Since you say it is working now, I'm going to assuming you are now using the C module. If this is not the case or if you would like to persue this issue further, feel free to reopen the issue.
